version: 2

models:
  - name: ghep_so_du_dau_ky_va_phat_sinh
    columns:
      - name: ky
      - name: dau_ky
      - name: thu_trong_ky
      - name: chi_trong_ky
      - name: phat_sinh_trong_ky
      - name: cuoi_ky

  - name: transformation_phat_sinh_step2.sql
    columns:
      - name: tk
      - name: nam
